ADD_SCENE(amiibo, file_browser, FILE_BROWSER)
ADD_SCENE(amiibo, file_browser_menu, FILE_BROWSER_MENU)
ADD_SCENE(amiibo, storage_list, STORAGE_LIST)
ADD_SCENE(amiibo, storage_list_menu, STORAGE_LIST_MENU)
// ADD_SCENE(amiibo, folder_list, FOLDER_LIST)
// ADD_SCENE(amiibo, folder_list_menu, FOLDER_LIST_MENU)
// ADD_SCENE(amiibo, amiibo_list, AMIIBO_LIST)
// ADD_SCENE(amiibo, amiibo_list_menu, AMIIBO_LIST_MENU)
ADD_SCENE(amiibo, amiibo_detail, AMIIBO_DETAIL)
ADD_SCENE(amiibo, amiibo_detail_menu, AMIIBO_DETAIL_MENU)