ADD_SCENE(amiidb, main, MAIN)
ADD_SCENE(amiidb, game_list, GAME_LIST)
ADD_SCENE(amiidb, amiibo_detail, AMIIBO_DETAIL)
ADD_SCENE(amiidb, amiibo_detail_menu, AMIIBO_DETAIL_MENU)
ADD_SCENE(amiidb, amiibo_search, AMIIBO_SEARCH)
ADD_SCENE(amiidb, fav_list, FAV_LIST)
ADD_SCENE(amiidb, fav_select, FAV_SELECT)
ADD_SCENE(amiidb, fav_list_menu, FAV_LIST_MENU)