ADD_SCENE(chameleon, main, MAIN)
ADD_SCENE(chameleon, menu, MENU)
ADD_SCENE(chameleon, menu_card_advanced, MENU_CARD_ADVANCED)
ADD_SCENE(chameleon, menu_card_slot, MENU_CARD_SLOT)
ADD_SCENE(chameleon, menu_card_data, MENU_CARD_DATA)
ADD_SCENE(chameleon, menu_card_type, MENU_CARD_TYPE)
ADD_SCENE(chameleon, menu_card_slot_select, MENU_CARD_SLOT_SELECT)
ADD_SCENE(chameleon, menu_card_write_mode_select, MENU_CARD_WRITE_MODE_SELECT)